name: DBNet
base: ['config/icdar2015.yaml']
arch:
  type: Model
  backbone:
    type: resnet50
    pretrained: true
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: DBHead
    out_channels: 2
    k: 50
post_processing:
  type: SegDetectorRepresenter
  args:
    thresh: 0.3
    box_thresh: 0.7
    max_candidates: 1000
    unclip_ratio: 1.5 # from paper
metric:
  type: QuadMetric
  args:
    is_output_polygon: false
loss:
  type: DBLoss
  alpha: 1
  beta: 10
  ohem_ratio: 3
optimizer:
  type: Adam
  args:
    lr: 0.002
    weight_decay: 0.0001
    amsgrad: true
lr_scheduler:
  type: WarmupPolyLR
  args:
    warmup_epoch: 1
trainer:
  seed: 2
  epochs: 10
  log_iter: 10
  show_images_iter: 5000
  resume_checkpoint: './output62/DBNet_resnet50_FPN_DBHead/checkpoint/model_latest.pth'
  finetune_checkpoint: ''
  output_dir: output62
  tensorboard: true
dataset:
  train:
    dataset:
      args:
        data_path:
          - ./train0.txt
        img_mode: RGB
    loader:
      batch_size: 2
      shuffle: true
      pin_memory: true
      num_workers: 0
      collate_fn: ''
  validate:
    dataset:
      args:
        data_path:
          - ./test0.txt
        pre_processes:
          - type: ResizeShortSize
            args:
              short_size: 552
              resize_text_polys: false
        img_mode: RGB
    loader:
      batch_size: 1
      shuffle: true
      pin_memory: false
      num_workers: 0
      collate_fn: ICDARCollectFN
